#!/usr/bin/env python

import os
import sys
import json
from datetime import datetime

import common


def main(hostname, username, private_key, key_type, path, source, job_dir):
    private_key = common.make_key_from(private_key, key_type)

    input_dir = os.path.join(job_dir, source)
    contents = os.listdir(input_dir)
    if len(contents) != 1:
        raise ValueError("Input directory to resource should contain exactly"
                         " one file.")

    input_file = os.path.join(input_dir, 'reference.link')
    with open(input_file) as fh:
        remote_path = fh.read().strip()
        filename = os.path.basename(remote_path)

    with common.make_sftp(hostname, username, private_key) as sftp:
        remote_attr = sftp.stat(remote_path)

    version = {'date': str(datetime.fromtimestamp(remote_attr.st_mtime))}

    return {'version': version,
            'metadata': [
                {'name': 'filename', 'value': filename},
                {'name': 'download',
                 'value': common.download_url(remote_path)}
            ]}


if __name__ == '__main__':
    options = json.load(sys.stdin)
    response = main(**options['source'], **options['params'],
                    job_dir=sys.argv[1])
    print(json.dumps(response))
